[profile.default]
src = "src"
out = "out"
libs = ["lib"]
tests = "test"
remappings = [
  "openzeppelin=lib/openzeppelin-contracts",
  "forge-std=lib/forge-std/src",
  "openzeppelin=lib/openzeppelin-contracts-upgradeable"
]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
